# Generated by Django 5.2.8 on 2025-12-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('title', models.CharField(max_length=200, verbose_name='Событие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='milestones/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Историческая веха',
                'verbose_name_plural': 'Исторические вехи',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя легенды')),
                ('position', models.CharField(choices=[('GK', 'Вратарь'), ('DEF', 'Защитник'), ('MID', 'Полузащитник'), ('FWD', 'Нападающий')], max_length=3, verbose_name='Позиция')),
                ('years_at_club', models.CharField(max_length=20, verbose_name='Годы в клубе')),
                ('image', models.ImageField(blank=True, null=True, upload_to='legends/', verbose_name='Фотография')),
                ('description', models.TextField(verbose_name='Описание')),
                ('achievements', models.TextField(verbose_name='Достижения')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Легенда',
                'verbose_name_plural': 'Легенды',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название трофея')),
                ('competition', models.CharField(choices=[('PL', 'Премьер-Лига'), ('FA', 'Кубок Англии'), ('LC', 'Кубок Лиги'), ('CL', 'Лига Чемпионов'), ('EL', 'Лига Европы'), ('CS', 'Суперкубок Англии'), ('CWC', 'Кубок Обладателей Кубков')], max_length=3, verbose_name='Турнир')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('years', models.TextField(help_text='Перечислите годы через запятую', verbose_name='Годы побед')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trophies/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Трофей',
                'verbose_name_plural': 'Трофеи',
                'ordering': ['competition'],
            },
        ),
    ]
